### PR TITLE
Added support for map os string type.

### PR DESCRIPTION
**Pull request by feamarto**
Added conform of maps of string types in the same manner as slices of string types are handled.
Respective unit tests were added to cover the new code.

### CODE REVIEW

**Comment by feamarto** [comment]
@leebenson 
Please consider this extension.
I have been using your package for quite some time now and a new version with this extension would help a lot.

**Comment by leebenson** [comment]
Thanks for your contribution! Could I trouble you to add an example to the README please, so others can be aware it exists? Thanks!

**Comment by feamarto** [comment]
Sure thing, I think there are still some tags not documented in the readme.
Mind if I add them as well? I know I saw a '!html' not there because I
wrote one myself and then noticed yours is better 🤣

I can get round to it on Monday I suppose.

**Comment by leebenson** [comment]
That'd be great, thank you! I'll leave this PR open in the meantime, and will merge once you've had a chance to add those changes. Thanks!

**Comment by feamarto** [comment]
README updated.
Added slices and maps to description as well ass '!html' and '!js' tags.

**Pull request merged**
